name: Fetch upstream Action
description: Syncs and merges your current repository with the upstream repository.
author: 135e2

inputs:
  upstream_repo:
    description: URL of gitHub public upstream repo 
    required: true
  upstream_branch:
    description: repo branch to fetch
    required: true
  local_branch:
    description: local repo branch
    required: true
  github_token:
    description: github push token
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.upstream_repo }}
    - ${{ inputs.upstream_branch }}
    - ${{ inputs.local_branch }}
    - ${{ inputs.github_token }}


branding:
  icon: 'git-merge'
  color: 'blue'
